@startuml
class designpatterns.SecurityManager {
- {static} SecurityManager instance
- SecurityManager()
+ {static} SecurityManager getInstance()
+ void login()
}


class designpatterns.App {
+ {static} void main(String[])
}

@enduml